version: '3'
services:
  nginx:
    build:
      context: .
    ports:
      - '80:80'
    volumes:
      - .:/www
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    volumes:
      - pgdata:/var/lib/postgresql/data

      # каталог с сокетом
      - /run/postgresql:/var/run/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    links:
    - db
    logging:
      options:
        max-size: 1m
volumes:
  pgdata:
    external: true
